/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Kms somesh
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public  menu() {
        initComponents();
        
        voterRadioButton.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            if (voterRadioButton.isSelected()) {
                voterlogin voterLogin = new voterlogin();
                voterLogin.setVisible(true);
            }
        }
    });
        adminRadioButton.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            if (adminRadioButton.isSelected()) {
                adminlogin adminLogin = new adminlogin();
                adminLogin.setVisible(true);
            }
        }
    });
        viewresultRadioButton.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            if (viewresultRadioButton.isSelected()) {
                viewresult viewResult = new viewresult();
                viewResult.setVisible(true);
            }
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        voterRadioButton = new javax.swing.JRadioButton();
        viewresultRadioButton = new javax.swing.JRadioButton();
        adminRadioButton = new javax.swing.JRadioButton();
        createuser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(voterRadioButton);
        voterRadioButton.setText("VOTER");
        getContentPane().add(voterRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        buttonGroup2.add(viewresultRadioButton);
        viewresultRadioButton.setText("VIEW RESULT");
        getContentPane().add(viewresultRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        buttonGroup2.add(adminRadioButton);
        adminRadioButton.setText("ELECTION ADMIN");
        getContentPane().add(adminRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        createuser.setText("CREATE USER");
        createuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createuserActionPerformed(evt);
            }
        });
        getContentPane().add(createuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jLabel3.setText("CLOSE");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kamat\\OneDrive\\Pictures\\Screenshots\\vote.png")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\kamat\\OneDrive\\Pictures\\Screenshots\\bg.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MousePressed

    private void createuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createuserActionPerformed
        // TODO add your handling code here:
        createuser createUserFrame = new createuser();
    
    // Set the visibility of the frame to true
    createUserFrame.setVisible(true);
    }//GEN-LAST:event_createuserActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminRadioButton;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton createuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton viewresultRadioButton;
    private javax.swing.JRadioButton voterRadioButton;
    // End of variables declaration//GEN-END:variables
}
